### ISSUE TITLE
Fiji crashes when converting from PointRoi to KeypointVector 

### ISSUE THREAD

**Issue by LauLauThom** [joheras/IJ-OpenCV#10]
I could not use the `PointRoiKeyPointVectorConverter()` in a jython macro without getting fiji to crash, eventhough the opposite conversion works.

```
roi2kp = PointRoiKeyPointVectorConverter()
NewKp  = roi2kp.convert(MultiPointRoi, KeyPointVector().__class__) # crashes
```
I have [reported it on fiji's forum](https://forum.image.sc/t/ij-opencv-crash-when-converting-from-pointroi-to-keypointvector/19346) too

**Comment by joheras** [comment]
Thanks for reporting this bug. 
I have updated the library and the problem should be fixed right now. 
Let me know if you have further problems.
Best,
Jónathan

**Comment by LauLauThom** [comment]
I finally had the time to test it, it is fixed indeed, thanks !
