### ISSUE TITLE
Add a wiki section

### ISSUE THREAD

**Issue by LauLauThom** [joheras/IJ-OpenCV#15]
Hi Jonathan,
I made a section about using IJ-OpenCV within Fiji in the [Jython scripting](https://imagej.net/Jython_Scripting) ImageJ wiki but since it is not limited to Jython I though that it would actually best here with the repository.

I transferred the content to my [fork](https://github.com/LauLauThom/IJ-OpenCV/wiki) just to give you an idea. I cannot do a pull request for the wiki unless the wiki is allowed for public editing, or for collaborators. 
Let me know if you could do one of those 2 ;)

I also added to my local fork the description line on top of the code section and some keywords , this could help to improve the visibility of the project as well I think ;)

**Comment by joheras** [comment]
Hi Laurent,

thanks a lot for your work.

I have added you as collaborator of the IJ-OpenCV repository, so you should
be able to edit the wiki now.

Thanks again.

Best,
Jónathan

**Comment by LauLauThom** [comment]
Thanks, I will transfer the changes ;)
