### ISSUE TITLE
Distribute XML for face detection classifier via Fiji updater  

### ISSUE THREAD

**Issue by LauLauThom** [joheras/IJ-OpenCV#17]
I noticed from a [post](https://forum.image.sc/t/installing-ij-opencv-javacv/23359/3?u=lthomas) on the forum that the [XML file](https://github.com/joheras/IJ-OpenCV/blob/master/src/main/java/ijopencv/examples/resources/haarcascade_frontalface_alt.xml) for the haar cascade classifier was not currently wrapped in the jar.

It turns out that the XML file was in the wrong folder and thus not picked by Maven ([see forum discussion](https://forum.image.sc/t/upload-a-xml-file-on-a-fiji-update-site/24251)). I moved it to the right location (see this [branch](https://github.com/LauLauThom/IJ-OpenCV/tree/XML_ressource))

But thinking of how the people could best reuse the code I think the best would be to distribute the XML file out of the jar, by putting it into the `Fiji.app/lib` folder as suggested by @imagejan in the forum thread mentioned above. 
This way it gets visible by the fiji-updater, and in the code you just refer to the file path (no `getResource` or unfamiliar java method).
In imageJ, the user would just need to create this folder `lib` in the ImageJ folder and put the XML there.

Here is an example of jython code in Fiji with the newly compiled jar from the branch mentioned above (the jar is available on the forum thread too).
```
from org.bytedeco.javacpp.opencv_objdetect import CascadeClassifier
from ijopencv.examples import FaceDetectionJ_
from ij import IJ
import os

# Accessing the XML from jar works but how to open a classifier from that ? (need to put into a file -> complicated)
print FaceDetectionJ_.getResource('haarcascade_frontalface_alt.xml') 
print FaceDetectionJ_.getResourceAsStream('haarcascade_frontalface_alt.xml')

# Or just putting the XML in the lib folder (can be distributed via the updater so)
XML_path = os.path.join(IJ.getDirectory("imagej"), 'lib', 'haarcascade_frontalface_alt.xml')  
Classifier = CascadeClassifier(XML_path) # now it's very easy to load the classifier file
print Classifier.empty() # False, OK the classifier is loaded
```

NB : If you validate the proposal, there is still this [line](https://github.com/LauLauThom/IJ-OpenCV/blob/07ed873558df5644378acdf7e10929f4bf4df2b9/src/main/java/ijopencv/examples/FaceDetectionJ_.java#L82) to update to use `Fiji.app/Lib/...xml`, I just dont know the java equivalent of the python `os.path.join`.

**Comment by joheras** [comment]
I have modified the code following your suggestions, and uploaded a new version of the plugin to the IJ-OpenCV repository, so the new version can be obtained with the ImageJ updater. 

Thanks for your work.
