### ISSUE TITLE
Mismatch to ImageJ Update site

### ISSUE THREAD

**Issue by l-jaye** [joheras/IJ-OpenCV#8]
Hello!

I noticed that the classes in the IJOpenCV.jar that ships from the ImageJ IJ-OpenCV-plugins Update site differs a lot from the version on here. I am wondering if its possible to add this one to the ImageJ Update site? Or, if there is a Maven artifact that corresponds to the ImageJ Update site version that I can access? Otherwise I'm having issues using IJ-OpenCV to build ImageJ projects in Eclipse.

Thank you!

**Comment by joheras** [comment]
Hi!

I have added this version of IJOpenCV.jar to the ImageJ Update site.

Let me know if you have further problems.

Best,
Jónathan

**Comment by l-jaye** [comment]
Hi Jonathan,

For some reason, the new file still contains the old class structure :(

Cheers,
Julia

**Comment by joheras** [comment]
Hi Julia,

sorry about that. I think that now I have uploaded the correct version with the new class structure. I am still changing some of the plugins, but at least you will be able to download the correct jar file for IJ-OpenCV now. 

Let me know if you have any further problem.

Best,
Jónathan

**Comment by l-jaye** [comment]
Hi Jonathan,

Yes, its the new .jar now! Thank you!

-Julia
